### ISSUE TITLE
mute colour of crossed out agenda items

### ISSUE THREAD

**Issue by michaelficarra** [ericf/timebox#2]
Any agenda item that is struck through should have colour `#bdb643` and anchors inside should have colour `#8ca6d8`. Screenshot shows normal agenda item, proposed crossed out agenda item, and current crossed out agenda item.

![screenshot from 2017-01-25 13-51-45](https://cloud.githubusercontent.com/assets/218840/22310838/6e1c5c98-e305-11e6-8fc7-9516a3b9fba8.png)

**Comment by ericf** [comment]
Good idea!

**Comment by michaelficarra** [comment]
Yeah, it was just hard to distinguish finished items from unfinished ones, so I added some custom CSS to distinguish them more easily. But I looked at the React code here, gave up, and just opened an issue.

**Comment by ericf** [comment]
Deployed the fix!

![screen shot 2017-01-25 at 10 05 38 pm](https://cloud.githubusercontent.com/assets/29096/22318670/74769fb4-e34a-11e6-92d7-81b87e835d80.png)

**Comment by michaelficarra** [comment]
Thanks! That's perfect.
